# Generated by Django 2.0.6 on 2018-11-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('sage', models.IntegerField()),
                ('sgender', models.CharField(default='black', max_length=20)),
            ],
        ),
    ]
